'use strict';
const topics=[
{id:'density',grade:'中1',name:'密度と物質の区別',description:'質量と体積から密度を求め、物質の種類を比べます。'},
{id:'gas',grade:'中1',name:'気体の性質',description:'気体の種類と集め方、空気に対する密度、水への溶けやすさを比較します。'},
{id:'solubility',grade:'中1',name:'溶解度と結晶',description:'水温と水の量を変え、溶ける量と冷却後に出る結晶量を調べます。'},
{id:'mass',grade:'中2',name:'質量保存の法則',description:'開放容器と密閉容器で、反応前後の質量の見え方を比較します。'},
{id:'oxidation',grade:'中2',name:'酸化と還元',description:'金属と酸素の結びつき、酸化物から酸素を取り除く変化を確かめます。'},
{id:'precipitation',grade:'中3',name:'イオンと沈殿',description:'2種類の水溶液を混ぜ、組み合わせによって沈殿が生じるか調べます。'},
{id:'electrolysis',grade:'中3',name:'電気分解',description:'電流と時間を変え、電極で発生する物質量の関係を観察します。'},
{id:'battery',grade:'中3',name:'化学電池',description:'2種類の金属と電解質を選び、電圧と電子の流れを比較します。'}
];
let current='density';
const $=s=>document.querySelector(s);
const list=$('#topic-list'), content=$('#lab-content');
function controlRange(id,label,min,max,step,value,unit=''){return `<div class="control-row"><label for="${id}"><span>${label}</span><output id="${id}-out">${value}${unit}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`}
function result(rows,note=''){return `<div class="result-card"><h3>結果</h3><div class="result-list">${rows.map(r=>`<div><span>${r[0]}</span><strong id="${r[2]||''}">${r[1]}</strong></div>`).join('')}</div>${note?`<div class="note-box" id="note">${note}</div>`:''}</div>`}
function bindRange(id,unit,fn){const el=$('#'+id),out=$('#'+id+'-out');el.addEventListener('input',()=>{out.value=el.value+unit;fn()})}
const gases={oxygen:['酸素','水上置換','空気より少し重い','溶けにくい'],hydrogen:['水素','水上置換','空気より非常に軽い','溶けにくい'],carbon:['二酸化炭素','下方置換','空気より重い','少し溶ける'],ammonia:['アンモニア','上方置換','空気より軽い','非常によく溶ける']};
const solubility={salt:t=>35.7+0.035*(t-20),nitrate:t=>13.3+0.75*t,sugar:t=>180+2.1*t};
function renderDensity(){content.innerHTML=`<div class="lab-grid"><div class="visual-card"><h3>密度の比較</h3><div class="bar-chart"><div class="bar-item"><div id="mass-bar" class="bar"></div><small>質量</small></div><div class="bar-item"><div id="volume-bar" class="bar"></div><small>体積</small></div><div class="bar-item"><div id="density-bar" class="bar"></div><small>密度</small></div></div></div><div><div class="control-card"><h3>条件</h3>${controlRange('mass','質量',10,500,1,100,' g')}${controlRange('volume','体積',10,250,1,50,' cm³')}</div>${result([['密度','2.00 g/cm³','density-result'],['推定される物質','アルミニウムに近い','material-result']], '密度 = 質量 ÷ 体積')}</div></div>`; const update=()=>{const m=+$('#mass').value,v=+$('#volume').value,d=m/v;$('#density-result').textContent=d.toFixed(2)+' g/cm³';const refs=[['アルミニウム',2.70],['鉄',7.87],['銅',8.96],['水',1.00],['エタノール',0.79]];refs.sort((a,b)=>Math.abs(a[1]-d)-Math.abs(b[1]-d));$('#material-result').textContent=refs[0][0]+'に近い';$('#mass-bar').style.height=Math.min(210,m/2.4)+'px';$('#volume-bar').style.height=Math.min(210,v*.84)+'px';$('#density-bar').style.height=Math.min(210,d*22)+'px'};bindRange('mass',' g',update);bindRange('volume',' cm³',update);update()}
function renderGas(){content.innerHTML=`<div class="lab-grid"><div class="visual-card"><h3>気体モデル</h3><div id="gas-box" class="gas-box"></div></div><div><div class="control-card"><h3>気体を選ぶ</h3><div class="control-row"><select id="gas-select">${Object.entries(gases).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select></div>${controlRange('gas-count','粒子数',8,45,1,24,' 個')}</div>${result([['適した集め方','水上置換','gas-method'],['空気との比較','少し重い','gas-density'],['水への溶けやすさ','溶けにくい','gas-water']], '気体の性質に応じて集め方を選びます。')}</div></div>`;const update=()=>{const g=gases[$('#gas-select').value],n=+$('#gas-count').value;$('#gas-method').textContent=g[1];$('#gas-density').textContent=g[2];$('#gas-water').textContent=g[3];const box=$('#gas-box');box.innerHTML=Array.from({length:n},(_,i)=>`<span class="gas-particle" style="left:${8+(i*37)%88}%;top:${8+(i*53)%82}%"></span>`).join('')};$('#gas-select').addEventListener('change',update);bindRange('gas-count',' 個',update);update()}
function renderSolubility(){content.innerHTML=`<div class="lab-grid"><div class="visual-card"><h3>水溶液と結晶</h3><div class="solution-cup"><div id="crystals"></div></div></div><div><div class="control-card"><h3>条件</h3><div class="control-row"><select id="solute"><option value="salt">食塩</option><option value="nitrate">硝酸カリウム</option><option value="sugar">砂糖</option></select></div>${controlRange('hot-temp','溶かす温度',20,80,1,60,' ℃')}${controlRange('cold-temp','冷やした温度',0,50,1,20,' ℃')}${controlRange('water-mass','水の質量',20,200,5,100,' g')}</div>${result([['高温で溶ける量','0 g','hot-sol'],['冷却後に溶けていられる量','0 g','cold-sol'],['出てくる結晶','0 g','crystal-result']], '温度による溶解度の差が大きい物質ほど再結晶に向きます。')}</div></div>`;const update=()=>{const f=solubility[$('#solute').value],h=+$('#hot-temp').value,c=+$('#cold-temp').value,w=+$('#water-mass').value,hot=f(h)*w/100,cold=f(c)*w/100,cr=Math.max(0,hot-cold);$('#hot-sol').textContent=hot.toFixed(1)+' g';$('#cold-sol').textContent=cold.toFixed(1)+' g';$('#crystal-result').textContent=cr.toFixed(1)+' g';$('#crystals').innerHTML=Array.from({length:Math.min(24,Math.round(cr/3))},(_,i)=>`<span class="crystal" style="left:${10+(i*31)%78}%;bottom:${8+(i%4)*18}px"></span>`).join('')};$('#solute').addEventListener('change',update);['hot-temp','cold-temp','water-mass'].forEach(id=>bindRange(id,id.includes('temp')?' ℃':' g',update));update()}
function renderMass(){content.innerHTML=`<div class="lab-grid"><div class="visual-card"><h3>反応前後の質量</h3><div class="mass-balance"><div class="mass-pan"><span>反応前</span><strong id="before-pan">150.0 g</strong></div><span>→</span><div class="mass-pan"><span>反応後</span><strong id="after-pan">150.0 g</strong></div></div></div><div><div class="control-card"><h3>条件</h3><div class="control-row"><select id="container-type"><option value="closed">密閉容器</option><option value="open">開放容器</option></select></div>${controlRange('reactant-mass','反応物の合計質量',50,300,1,150,' g')}${controlRange('gas-produced','発生する気体',0,50,1,20,' g')}</div>${result([['反応前','150.0 g','before-result'],['測定される反応後','150.0 g','after-result'],['系全体の質量','150.0 g','total-result']], '密閉した系全体では、化学変化の前後で質量は変わりません。')}</div></div>`;const update=()=>{const m=+$('#reactant-mass').value,g=+$('#gas-produced').value,open=$('#container-type').value==='open',after=open?m-g:m;['before-pan','before-result','total-result'].forEach(id=>$('#'+id).textContent=m.toFixed(1)+' g');['after-pan','after-result'].forEach(id=>$('#'+id).textContent=after.toFixed(1)+' g');$('#note').textContent=open?'気体が容器外へ出るため、容器だけを量ると軽く見えます。':'密閉しているため、発生した気体も含めた質量は変わりません。'};$('#container-type').addEventListener('change',update);bindRange('reactant-mass',' g',update);bindRange('gas-produced',' g',update);update()}
function renderOxidation(){content.innerHTML=`<div class="lab-grid"><div class="visual-card"><h3>金属の変化</h3><div class="oxide-demo"><div id="metal-piece" class="metal-piece"></div></div></div><div><div class="control-card"><h3>条件</h3><div class="control-row"><select id="reaction-mode"><option value="oxidation">酸化</option><option value="reduction">還元</option></select></div>${controlRange('reaction-progress','反応の進み方',0,100,1,50,' %')}</div>${result([['変化','金属が酸素と結びつく','change-result'],['質量の変化','増える','mass-change'],['粒子の見方','金属原子 + 酸素原子','particle-result']], '酸化は酸素と結びつく変化、還元は酸化物から酸素を取り除く変化です。')}</div></div>`;const update=()=>{const red=$('#reaction-mode').value==='reduction',p=+$('#reaction-progress').value;$('#metal-piece').classList.toggle('oxidized',red?p<50:p>50);$('#metal-piece').style.opacity=.65+p/285;$('#change-result').textContent=red?'酸化物から酸素を取り除く':'金属が酸素と結びつく';$('#mass-change').textContent=red?'減る':'増える';$('#particle-result').textContent=red?'金属酸化物 → 金属 + 酸素':'金属 + 酸素 → 金属酸化物'};$('#reaction-mode').addEventListener('change',update);bindRange('reaction-progress',' %',update);update()}
function renderPrecipitation(){const pairs={silver:['硝酸銀水溶液 + 塩化ナトリウム水溶液','塩化銀','白色'],barium:['塩化バリウム水溶液 + 硫酸ナトリウム水溶液','硫酸バリウム','白色'],copper:['硫酸銅水溶液 + 水酸化ナトリウム水溶液','水酸化銅','青白色'],none:['塩化ナトリウム水溶液 + 硝酸カリウム水溶液','沈殿なし','変化なし']};content.innerHTML=`<div class="lab-grid"><div class="visual-card"><h3>混合後のようす</h3><div class="solution-cup"><div id="precipitate" class="precipitate"></div></div></div><div><div class="control-card"><h3>水溶液の組み合わせ</h3><div class="control-row"><select id="pair-select">${Object.entries(pairs).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select></div>${controlRange('mix-volume','混ぜる量',10,100,5,50,' mL')}</div>${result([['生成物','塩化銀','precipitate-name'],['見た目','白色の沈殿','precipitate-color'],['反応に関わるイオン','Ag⁺ + Cl⁻','ion-equation']], '水に溶けにくい物質ができると沈殿として現れます。')}</div></div>`;const eq={silver:'Ag⁺ + Cl⁻',barium:'Ba²⁺ + SO₄²⁻',copper:'Cu²⁺ + 2OH⁻',none:'反応なし'};const update=()=>{const k=$('#pair-select').value,p=pairs[k],v=+$('#mix-volume').value;$('#precipitate-name').textContent=p[1];$('#precipitate-color').textContent=p[2]+(k==='none'?'':'の沈殿');$('#ion-equation').textContent=eq[k];$('#precipitate').style.height=k==='none'?'0':Math.min(90,v*.8)+'px';$('#precipitate').style.background=k==='copper'?'#9fd3df':'#f2f0df'};$('#pair-select').addEventListener('change',update);bindRange('mix-volume',' mL',update);update()}
function renderElectrolysis(){content.innerHTML=`<div class="lab-grid"><div class="visual-card"><h3>電極付近の変化</h3><div class="electrode-box"><div class="electrode"><div id="left-bubbles" class="bubble-column"></div></div><div class="electrode"><div id="right-bubbles" class="bubble-column"></div></div></div></div><div><div class="control-card"><h3>条件</h3><div class="control-row"><select id="electrolyte"><option value="water">水の電気分解</option><option value="copper">塩化銅水溶液</option></select></div>${controlRange('current','電流',0.1,2,0.1,1,' A')}${controlRange('time','時間',10,180,10,60,' s')}</div>${result([['陰極','水素','cathode-result'],['陽極','酸素','anode-result'],['発生量の目安','60 単位','amount-result']], '流れた電気量が多いほど、電極で起こる変化も大きくなります。')}</div></div>`;const update=()=>{const copper=$('#electrolyte').value==='copper',q=+$('#current').value*+$('#time').value,n=Math.min(25,Math.round(q/5));$('#cathode-result').textContent=copper?'銅が付着':'水素';$('#anode-result').textContent=copper?'塩素':'酸素';$('#amount-result').textContent=q.toFixed(1)+' 単位';const bubbles=Array.from({length:n},(_,i)=>`<span class="bubble-dot" style="left:${(i%3)*10-10}px;bottom:${i*7}px"></span>`).join('');$('#left-bubbles').innerHTML=copper?'':bubbles;$('#right-bubbles').innerHTML=bubbles};$('#electrolyte').addEventListener('change',update);bindRange('current',' A',update);bindRange('time',' s',update);update()}
function renderBattery(){const potential={mg:-2.37,zn:-0.76,fe:-0.44,cu:0.34};content.innerHTML=`<div class="lab-grid"><div class="visual-card"><h3>化学電池</h3><div class="battery-box"><div id="metal-a-view" class="battery-metal" style="background:#aab5ba"></div><div id="metal-b-view" class="battery-metal" style="background:#b87333"></div><div class="battery-wire"></div><div id="lamp" class="lamp"></div></div></div><div><div class="control-card"><h3>条件</h3><div class="control-row"><label>金属A</label><select id="metal-a"><option value="zn">亜鉛</option><option value="mg">マグネシウム</option><option value="fe">鉄</option><option value="cu">銅</option></select></div><div class="control-row"><label>金属B</label><select id="metal-b"><option value="cu">銅</option><option value="fe">鉄</option><option value="zn">亜鉛</option><option value="mg">マグネシウム</option></select></div><div class="control-row"><select id="electrolyte-battery"><option value="1">電解質水溶液</option><option value="0">純水</option></select></div></div>${result([['電圧の目安','1.10 V','voltage-result'],['電子を出しやすい金属','亜鉛','negative-result'],['電流','流れる','current-result']], '異なる金属と電解質を組み合わせると、化学エネルギーを電気エネルギーへ変えられます。')}</div></div>`;const names={mg:'マグネシウム',zn:'亜鉛',fe:'鉄',cu:'銅'},colors={mg:'#c8ced1',zn:'#aab5ba',fe:'#777f83',cu:'#b87333'};const update=()=>{const a=$('#metal-a').value,b=$('#metal-b').value,e=+$('#electrolyte-battery').value,v=e*Math.abs(potential[a]-potential[b]),on=v>.05;$('#voltage-result').textContent=v.toFixed(2)+' V';$('#negative-result').textContent=potential[a]<potential[b]?names[a]:potential[b]<potential[a]?names[b]:'同じ金属';$('#current-result').textContent=on?'流れる':'流れない';$('#lamp').classList.toggle('on',on);$('#metal-a-view').style.background=colors[a];$('#metal-b-view').style.background=colors[b]};['metal-a','metal-b','electrolyte-battery'].forEach(id=>$('#'+id).addEventListener('change',update));update()}
const renders={density:renderDensity,gas:renderGas,solubility:renderSolubility,mass:renderMass,oxidation:renderOxidation,precipitation:renderPrecipitation,electrolysis:renderElectrolysis,battery:renderBattery};
function openTopic(id){current=id;const t=topics.find(x=>x.id===id);$('#grade-label').textContent=t.grade+' 化学';$('#lab-title').textContent=t.name;$('#lab-description').textContent=t.description;document.querySelectorAll('.topic-button').forEach(b=>b.classList.toggle('is-active',b.dataset.id===id));renders[id]()}
list.innerHTML=topics.map((t,i)=>`<button class="topic-button" data-id="${t.id}" type="button"><span class="topic-number">${String(i+1).padStart(2,'0')}</span><span class="topic-name">${t.name}<small class="topic-grade">${t.grade}</small></span></button>`).join('');
list.addEventListener('click',e=>{const b=e.target.closest('.topic-button');if(b)openTopic(b.dataset.id)});$('#reset-lab').addEventListener('click',()=>openTopic(current));openTopic(current);
